spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lucky_share?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: landicorp
zuul:
  sensitive-headers: "Cookie", "Set-Cookie", "Authorization"
  routes:
    lucky-user: /user/**
    lucky-content: /content/**
    lucky-bonus: /bonus/**
management:
  security:
    enabled: false  
  