spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lucky_share?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
zuul:
  # 如果这个为空，zuul会把头部信息转发给其它服务
  sensitive-headers:
  routes:
    lucky-user:
      path: /user/**
      strip-prefix: false
    lucky-content:
      path: /content/**
      strip-prefix: false
    lucky-bonus:
      path: /bonus/**
      strip-prefix: false
management:
  security:
    enabled: false  
  